<?xml version="1.0"?>
<package format="2">

  <name>tf_tools</name>
  <version>0.0.4</version>
  <description>ROS tools and scripts relates to tf</description>
  <maintainer email="bo-miquel.nordfeldt@uib.es">Bo Miquel Nordfeldt-Fiol</maintainer>

  <license>BSD-4-Clause</license>

  <url type="website">http://ros.org/wiki/tf_tools</url>
  <url type="bugtracker">https://github.com/srv/srv_tools/issues</url>
  <url type="repository">https://github.com/srv/srv_tools</url>

  <author email="stwirth@uib.es">Stephan Wirth</author>
  <author email="miquel.massot@uib.es">Miquel Massot</author>

  <!-- Build tool -->
  <buildtool_depend>catkin</buildtool_depend>

  <!-- Build dependencies -->
  <build_depend>tf</build_depend>
  <build_depend>nav_msgs</build_depend>
  
  <!-- Exec dependencies -->
  <exec_depend>tf</exec_depend>
  <exec_depend>nav_msgs</exec_depend>

  <export>
  </export>
  
</package>
