<?xml version="1.0"?>
<package format="2">

  <name>plot_tools</name>
  <version>0.0.3</version>
  <description>plot_tools</description>
  <maintainer email="bo-miquel.nordfeldt@uib.cat">Bo Miquel Nordfeldt-Fiol</maintainer>

  <license>BSD</license>

  <url type="website">http://ros.org/wiki/plot_tools</url>
  <!-- <url type="bugtracker"></url> -->

  <author>Pep Lluis Negre</author>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>rospy</build_depend>

  <exec_depend>rospy</exec_depend>

  <export>
  </export>
  
</package>
