name: CI

on:
  # direct pushes to protected branches are not supported
  pull_request:
  push:
  workflow_dispatch:

jobs:
  i_ci:
    name: ubuntu_bionic (${{ matrix.ros_repo }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ros_distro: [ melodic, noetic ]
        ros_repo: [ main, testing ]

    env:
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
      CATKIN_LINT: "true"
      CATKIN_LINT_ARGS: --ignore launch_depend

    steps:
      - name: Fetch repository
        uses: actions/checkout@v2

      - name: ccache cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          # we always want the ccache cache to be persisted, as we cannot easily
          # determine whether dependencies have changed, and ccache will manage
          # updating the cache for us. Adding 'run_id' to the key will force an
          # upload at the end of the job.
          key: ccache-${{ matrix.ros_distro }}-${{ matrix.ros_repo }}-${{github.run_id}}
          restore-keys: |
            ccache-${{ matrix.ros_distro }}-${{ matrix.ros_repo }}

      - name: Run industrial_ci
        uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: ${{ matrix.ros_distro }}
          ROS_REPO: ${{ matrix.ros_repo }}
